name: "Vinyl Streamer"
description: "Stream audio from USB input to Icecast (FFmpeg + Icecast)"
version: "1.7.0"
slug: "vinyl-streamer"
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - i386
url: "https://github.com/owanvik/ha-addons"
startup: application
boot: auto
audio: true
full_access: true
hassio_api: true
map:
  - share:rw
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Icecast HTTP stream"
options:
  station_name: "Vinyl Radio"
  station_description: "Streaming from vinyl player"
  mount_point: "/vinyl"
  audio_samplerate: 44100
  audio_channels: 2
  audio_bitrate: 320
  icecast_password: "hackme"
  low_latency: false
  noise_reduction:
    highpass_enabled: false
    highpass_freq: 30
    lowpass_enabled: false
    lowpass_freq: 16000
    denoise_enabled: false
    denoise_strength: 0.3
schema:
  station_name: str
  station_description: str
  mount_point: str
  audio_samplerate: select(44100|48000)
  audio_channels: select(1|2)
  audio_bitrate: select(128|192|256|320)
  icecast_password: password
  low_latency: bool
  noise_reduction:
    highpass_enabled: bool
    highpass_freq: int(20,100)
    lowpass_enabled: bool
    lowpass_freq: int(10000,20000)
    denoise_enabled: bool
    denoise_strength: float(0.1,1.0)
